CREATE DATABASE NATURE;

/* --------------------------------------------- */

USE NATURE;

/* --------------------------------------------- */

DROP TABLE ARTICLES_AUTHORS;
DROP TABLE ARTICLES;
DROP TABLE AUTHORS;
DROP TABLE TITLEWORDS;
DROP PROCEDURE AddOrIncrementWord;

/* --------------------------------------------- */;

CREATE TABLE ARTICLES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DOI VARCHAR(30) NOT NULL UNIQUE,
    TITLE VARCHAR(255) NOT NULL,
    TITLE_LINK VARCHAR(100) NOT NULL,
    FIRST_FIRSTNAME VARCHAR(30) NOT NULL,
    FIRST_LASTNAME VARCHAR(30) NOT NULL,
    SECOND_FIRSTNAME VARCHAR(30),
    SECOND_LASTNAME VARCHAR(30),
    THIRD_FIRSTNAME VARCHAR(30),
    THIRD_LASTNAME VARCHAR(30),
    ARTICLE_TYPE VARCHAR(30) NOT NULL,
    RECEIVED DATE,
    ACCEPTED DATE,
    PUBLISHED DATE,
    ACCESSES INT,
    ALTMETRIC INT,
    JOURNAL VARCHAR(50) NOT NULL
);
ALTER TABLE ARTICLES ADD INDEX (DOI);

/* --------------------------------------------- */

CREATE TABLE AUTHORS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    ORCID VARCHAR(50) UNIQUE
);
ALTER TABLE AUTHORS ADD INDEX (FIRSTNAME, LASTNAME);

/* --------------------------------------------- */

DELIMITER //

CREATE TRIGGER truncate_title_before_insert
BEFORE INSERT ON AUTHORS
FOR EACH ROW
BEGIN
    IF CHAR_LENGTH(NEW.FIRSTNAME) > 30 THEN
        SET NEW.FIRSTNAME = LEFT(NEW.FIRSTNAME, 30);
    END IF;
END;
//

DELIMITER ;

/* --------------------------------------------- */

CREATE TABLE ARTICLES_AUTHORS (
    -- ID INT PRIMARY KEY AUTO_INCREMENT,
    ARTICLE_ID INT NOT NULL,
    AUTHOR_ID INT NOT NULL,
    CONSTRAINT PK_ARTICLES_AUTHORS PRIMARY KEY (ARTICLE_ID, AUTHOR_ID),
    CONSTRAINT FK_ARTICLE_ID FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID),
    CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID)
);

/* --------------------------------------------- */

CREATE TABLE TITLEWORDS (
    WORD VARCHAR(20) PRIMARY KEY,
    WORDCOUNT INT NOT NULL
);

DELIMITER //

CREATE PROCEDURE AddOrIncrementWord(IN w VARCHAR(20))
BEGIN
    INSERT INTO TITLEWORDS (WORD, WORDCOUNT)
    VALUES (w, 1)
    ON DUPLICATE KEY UPDATE WORDCOUNT = WORDCOUNT + 1;
END
//

DELIMITER ;

/* --------------------------------------------- */;
